name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: "Node ${{ matrix.node }} on Linux: Test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: browser-actions/setup-firefox@latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
      - run: ng e2e



        
   
